# Generated by Django 5.2.1 on 2025-06-01 22:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0002_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistenciaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('presente', models.BooleanField(default=False)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='jardinaplicacion.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='jardinaplicacion.curso')),
                ('maestro', models.ForeignKey(limit_choices_to={'es_maestro': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'alumno__apellido', 'alumno__nombre'],
                'unique_together': {('alumno', 'fecha')},
            },
        ),
    ]
