# Generated by Django 5.2.1 on 2025-06-02 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0003_registroasistenciaalumno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroasistenciamaestro',
            options={'ordering': ['-fecha', 'curso__nombre', '-hora_ingreso']},
        ),
        migrations.AlterUniqueTogether(
            name='registroasistenciamaestro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroasistenciamaestro',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia_maestros', to='jardinaplicacion.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroasistenciamaestro',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistenciamaestro',
            unique_together={('maestro', 'curso', 'fecha')},
        ),
    ]
