# Generated by Django 5.2.1 on 2025-06-03 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0004_alter_registroasistenciamaestro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoDirectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida')], max_length=10)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_procesado', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_directivo', to='jardinaplicacion.curso')),
                ('maestro', models.ForeignKey(limit_choices_to={'es_maestro': True}, on_delete=django.db.models.deletion.CASCADE, related_name='avisos_enviados', to=settings.AUTH_USER_MODEL)),
                ('procesado_por', models.ForeignKey(blank=True, limit_choices_to={'es_directivo': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'curso__nombre'],
                'unique_together': {('maestro', 'curso', 'fecha', 'tipo')},
            },
        ),
    ]
