# Generated by Django 5.2.1 on 2025-06-03 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0005_avisodirectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisodirectivo',
            name='hora_aviso',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
