# Generated by Django 5.2.1 on 2025-06-03 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0006_avisodirectivo_hora_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisodirectivo',
            name='hora_aviso',
        ),
    ]
