# Generated by Django 5.2.1 on 2025-06-04 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0007_remove_avisodirectivo_hora_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisodirectivo',
            name='hora_solicitada',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
    ]
