# Generated by Django 5.2.1 on 2025-06-04 21:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0008_avisodirectivo_hora_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cuota mensual del curso en pesos', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
