# Generated by Django 5.2.1 on 2025-06-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0009_curso_cuota_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistenciamaestro',
            name='ausente',
            field=models.BooleanField(default=False),
        ),
    ]
