# Generated by Django 5.2.1 on 2025-06-06 21:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0010_registroasistenciamaestro_ausente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuotacurso',
            options={'ordering': ['-año', '-mes']},
        ),
        migrations.AlterModelOptions(
            name='pagocuota',
            options={'ordering': ['-fecha_pago']},
        ),
        migrations.AddField(
            model_name='cuotacurso',
            name='fecha_vencimiento',
            field=models.DateField(default='2025-05-20', help_text='Fecha límite para pagar esta cuota sin atraso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='dia_vencimiento_cuota',
            field=models.PositiveIntegerField(default=10, help_text='Día del mes límite para pagar la cuota (máximo día 28 para evitar problemas con febrero)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='dias_atraso_pago',
            field=models.PositiveIntegerField(default=0, help_text='Días de atraso que tenía cuando se realizó el pago'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='estado_pago',
            field=models.CharField(choices=[('a_tiempo', 'Pagado a tiempo'), ('con_atraso', 'Pagado con atraso')], default='a_tiempo', max_length=20),
        ),
        migrations.CreateModel(
            name='DeudorCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_marcado_deudor', models.DateTimeField(auto_now_add=True)),
                ('dias_atraso', models.PositiveIntegerField(default=0)),
                ('monto_adeudado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='jardinaplicacion.alumno')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudores', to='jardinaplicacion.cuotacurso')),
            ],
            options={
                'ordering': ['-fecha_marcado_deudor'],
                'unique_together': {('alumno', 'cuota')},
            },
        ),
    ]
