# Generated by Django 5.2.2 on 2025-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0011_alter_cuotacurso_options_alter_pagocuota_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='edad_sala',
            field=models.PositiveIntegerField(choices=[(0, 'meses (0-11 meses)'), (1, '1 año'), (2, '2 años'), (3, '3 años'), (4, '4 años'), (5, '5 años')]),
        ),
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('intermedio', 'Intermedio'), ('tarde', 'Tarde')], max_length=10),
        ),
    ]
