# Generated by Django 5.2.2 on 2025-06-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroretiroalumno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='retiros_curso', to='jardinaplicacion.curso'),
            preserve_default=False,
        ),
    ]
