# Generated by Django 5.2.3 on 2025-06-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinaplicacion', '0014_registroretiroalumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones sobre el alumno'),
        ),
    ]
